image: node:alpine

stages:
  - test
  - deploy

lint:
  stage: test
  script:
    - yarn
    - yarn lint

test:
  stage: test
  script:
    - yarn
    - yarn test

deploy_to_screeps:
  stage: deploy
  only:
    refs:
      - master
  script:
    - ./deploy.sh
